Ideas for Initial Values (not working yet):
Version 1+2 (same Idea different implementation due to errors):
Provide a localfunction and use the Dune::Fem::interpolate(function, solution)
error:
dune-diffusionfem: /usr/local/include/dune/fem/quadrature/quadprovider.hh:56: QuadImp &Dune::Fem::QuadCreator<1>::QuadratureStorage<Dune::Fem::CubeQuadrature<double, 2> >::getQuadrature(const Dune::GeometryType &, unsigned int) [dummy = 1, QuadImp = Dune::Fem::CubeQuadrature<double, 2>]: Assertion `order < storage_.size()' failed.

Version 3:
initialize the value directly (without Dune::Fem::interpolate(function, solution) )
error:
/home/js/dune/dune-diffusionfem/src/dune-diffusionfem.cc:115:30: error: type 'Dune::Fem::LocalFunctionAdapterLocalFunction<Dune::Fem::LocalAnalyticalFunctionBinder<Dune::Fem::DiscreteFunctionSpaceAdapter<Dune::Fem::FunctionSpace<double, double, 2, 1>, Dune::Fem::AdaptiveLeafGridPart<Dune::YaspGrid<2, Dune::EquidistantCoordinates<double, 2> >, Dune::PartitionIteratorType::All_Partition, false> >, std::function<Dune::FieldVector<double, 1> (const Dune::FieldVector<double, 2> &, const double &, const Dune::Entity<0, 2, const Dune::YaspGrid<2, Dune::EquidistantCoordinates<double, 2> >, YaspEntity> &)> > >' does not provide a subscript operator